export const adminCopy = {
  ar: {
    brand: "طبخة آند مور",
    product: "إدارة القائمة",
    signIn: "تسجيل الدخول",
    signInHint: "للمطعم فقط. الضيوف يستخدمون القائمة عبر رمز QR.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    logout: "خروج",
    overview: "نظرة عامة",
    menu: "الأطباق",
    categories: "الأقسام",
    settings: "الإعدادات",
    preview: "معاينة",
    addDish: "إضافة طبق",
    addCategory: "إضافة قسم",
    manageMenu: "إدارة القائمة",
    previewMenu: "معاينة القائمة",
    saveDraft: "حفظ مسودة",
    publish: "نشر",
    unpublish: "إلغاء النشر",
    saving: "جاري الحفظ…",
    saved: "تم الحفظ",
    published: "منشور",
    draft: "مسودة",
    available: "متوفر",
    unavailable: "غير متوفر",
    featured: "مميّز",
    active: "ظاهر",
    hidden: "مخفي",
    search: "بحث",
    filter: "تصفية",
    allCategories: "كل الأقسام",
    allStatus: "كل الحالات",
    missingEnglish: "بدون اسم إنجليزي",
    missingImage: "بدون صورة",
    needsReview: "يحتاج مراجعة",
    arabic: "العربية",
    english: "English",
    nameAr: "الاسم بالعربية",
    nameEn: "الاسم بالإنجليزية",
    descriptionAr: "الوصف بالعربية",
    descriptionEn: "الوصف بالإنجليزية",
    price: "السعر",
    currency: "العملة",
    category: "القسم",
    portionNote: "ملاحظة الكمية",
    dietaryTags: "وسوم غذائية",
    allergens: "مسببات الحساسية",
    spicyLevel: "حرارة التوابل",
    image: "الصورة",
    upload: "رفع صورة",
    replace: "استبدال",
    removeImage: "إزالة الصورة",
    surface: "خلفية القسم",
    cream: "كريمي",
    forest: "أخضر داكن",
    scriptAccent: "عبارة جانبية",
    cancel: "إلغاء",
    delete: "حذف",
    duplicate: "نسخ",
    edit: "تعديل",
    confirm: "تأكيد",
    close: "إغلاق",
    actions: "إجراءات",
    lastUpdated: "آخر تحديث",
    totalCategories: "الأقسام",
    totalDishes: "الأطباق",
    activeDishes: "أطباق ظاهرة",
    unavailableDishes: "غير متوفرة",
    featuredDishes: "مميّزة",
    withoutPhotos: "بدون صور",
    missingEnCount: "بدون إنجليزي",
    emptyDishes: "لا توجد أطباق بعد.",
    emptyCategories: "لا توجد أقسام بعد.",
    emptySearch: "لا نتائج لهذا البحث.",
    addFirstDish: "أضف أول طبق",
    addFirstCategory: "أضف أول قسم",
    deleteDishTitle: "حذف هذا الطبق؟",
    deleteDishBody: "سيختفي من القائمة المنشورة. لا يمكن التراجع.",
    deleteCategoryTitle: "حذف هذا القسم؟",
    deleteCategoryBody: "لن يُحذف القسم إذا بقيت فيه أطباق. انقلها أولاً.",
    reassign: "نقل الأطباق إلى",
    bulk: "تحديد",
    bulkShow: "إظهار المحدد",
    bulkHide: "إخفاء المحدد",
    bulkMove: "نقل إلى قسم",
    bulkDelete: "حذف المحدد",
    selected: "محدّد",
    draftPreview: "معاينة المسودة",
    previewHint: "هذه المعاينة تشمل المسودات. الضيوف يرون النسخة المنشورة فقط.",
    mobile: "جوال",
    desktop: "سطح المكتب",
    restaurantNameAr: "اسم المطعم بالعربية",
    restaurantNameEn: "اسم المطعم بالإنجليزية",
    taglineAr: "الشعار بالعربية",
    taglineEn: "الشعار بالإنجليزية",
    storyAr: "قصة المطعم بالعربية",
    storyEn: "قصة المطعم بالإنجليزية",
    defaultLanguage: "اللغة الافتراضية",
    qrUrl: "رابط رمز QR",
    qrUrlHint: "يجب أن يشير إلى القائمة العامة (/ar) وليس لوحة الإدارة.",
    phone: "الهاتف",
    instagram: "إنستغرام",
    addressAr: "العنوان بالعربية",
    addressEn: "العنوان بالإنجليزية",
    logo: "الشعار",
    sessionExpired: "انتهت الجلسة. سجّل الدخول مرة أخرى.",
    invalidCredentials: "البريد أو كلمة المرور غير صحيحة.",
    networkError: "تعذّر الاتصال. تحقق من الشبكة.",
    validationError: "راجع الحقول المظللة.",
    uploadError: "تعذّر رفع الصورة.",
    optional: "اختياري",
    englishNullable: "يمكن تركه فارغاً. لا تُخترع ترجمة.",
    reviewBanner: "مسائل محتوى معروفة من القائمة المطبوعة تبقى كما هي حتى يقرر المطعم تعديلها.",
    hideShow: "إظهار / إخفاء",
    orderHint: "اسحب لإعادة الترتيب. يظهر الترتيب في قائمة الضيوف بعد النشر.",
    status: "الحالة",
    none: "بدون",
    spicy0: "بدون",
    spicy1: "خفيف",
    spicy2: "متوسط",
    spicy3: "حار",
    back: "رجوع",
    newDish: "طبق جديد",
    newCategory: "قسم جديد",
    editDish: "تعديل طبق",
    editCategory: "تعديل قسم",
    confirmBulkDelete: "حذف الأطباق المحددة؟ لا يمكن التراجع.",
    liveNote: "الضيوف يرون المنشور والمتوفر فقط.",
    quickAdd: "إضافة سريعة",
  },
  en: {
    brand: "Tabkha and More",
    product: "Menu studio",
    signIn: "Sign in",
    signInHint: "Staff only. Guests open the menu from the table QR.",
    email: "Email",
    password: "Password",
    logout: "Sign out",
    overview: "Overview",
    menu: "Dishes",
    categories: "Categories",
    settings: "Settings",
    preview: "Preview",
    addDish: "Add dish",
    addCategory: "Add category",
    manageMenu: "Manage menu",
    previewMenu: "Preview menu",
    saveDraft: "Save draft",
    publish: "Publish",
    unpublish: "Unpublish",
    saving: "Saving…",
    saved: "Saved",
    published: "Published",
    draft: "Draft",
    available: "Available",
    unavailable: "Unavailable",
    featured: "Featured",
    active: "Visible",
    hidden: "Hidden",
    search: "Search",
    filter: "Filter",
    allCategories: "All categories",
    allStatus: "Any status",
    missingEnglish: "Missing English",
    missingImage: "Missing photo",
    needsReview: "Needs review",
    arabic: "Arabic",
    english: "English",
    nameAr: "Arabic name",
    nameEn: "English name",
    descriptionAr: "Arabic description",
    descriptionEn: "English description",
    price: "Price",
    currency: "Currency",
    category: "Category",
    portionNote: "Portion note",
    dietaryTags: "Dietary tags",
    allergens: "Allergens",
    spicyLevel: "Spice",
    image: "Photo",
    upload: "Upload photo",
    replace: "Replace",
    removeImage: "Remove photo",
    surface: "Section surface",
    cream: "Cream",
    forest: "Forest",
    scriptAccent: "Accent line",
    cancel: "Cancel",
    delete: "Delete",
    duplicate: "Duplicate",
    edit: "Edit",
    confirm: "Confirm",
    close: "Close",
    actions: "Actions",
    lastUpdated: "Last updated",
    totalCategories: "Categories",
    totalDishes: "Dishes",
    activeDishes: "Live dishes",
    unavailableDishes: "Unavailable",
    featuredDishes: "Featured",
    withoutPhotos: "Without photos",
    missingEnCount: "Missing English",
    emptyDishes: "No dishes yet.",
    emptyCategories: "No categories yet.",
    emptySearch: "Nothing matches this search.",
    addFirstDish: "Add the first dish",
    addFirstCategory: "Add the first category",
    deleteDishTitle: "Delete this dish?",
    deleteDishBody: "It will disappear from the published menu. This cannot be undone.",
    deleteCategoryTitle: "Delete this category?",
    deleteCategoryBody: "A category with dishes cannot be deleted. Move the dishes first.",
    reassign: "Move dishes to",
    bulk: "Select",
    bulkShow: "Show selected",
    bulkHide: "Hide selected",
    bulkMove: "Move to category",
    bulkDelete: "Delete selected",
    selected: "selected",
    draftPreview: "Draft preview",
    previewHint: "Preview includes drafts. Guests only see the published menu.",
    mobile: "Mobile",
    desktop: "Desktop",
    restaurantNameAr: "Restaurant name (Arabic)",
    restaurantNameEn: "Restaurant name (English)",
    taglineAr: "Tagline (Arabic)",
    taglineEn: "Tagline (English)",
    storyAr: "Story (Arabic)",
    storyEn: "Story (English)",
    defaultLanguage: "Default language",
    qrUrl: "QR destination URL",
    qrUrlHint: "Must point at the public menu (/ar), never /admin.",
    phone: "Phone",
    instagram: "Instagram",
    addressAr: "Address (Arabic)",
    addressEn: "Address (English)",
    logo: "Logo",
    sessionExpired: "Your session ended. Please sign in again.",
    invalidCredentials: "Email or password is incorrect.",
    networkError: "Could not reach the server. Check the connection.",
    validationError: "Please check the highlighted fields.",
    uploadError: "The photo could not be uploaded.",
    optional: "optional",
    englishNullable: "May be left empty. Do not invent a translation.",
    reviewBanner: "Known print-menu discrepancies stay as-is until the restaurant chooses to edit them.",
    hideShow: "Show / hide",
    orderHint: "Drag to reorder. Guests see this order after you publish.",
    status: "Status",
    none: "None",
    spicy0: "None",
    spicy1: "Mild",
    spicy2: "Medium",
    spicy3: "Hot",
    back: "Back",
    newDish: "New dish",
    newCategory: "New category",
    editDish: "Edit dish",
    editCategory: "Edit category",
    confirmBulkDelete: "Delete the selected dishes? This cannot be undone.",
    liveNote: "Guests see published, available dishes only.",
    quickAdd: "Quick add",
  },
} as const;

export type AdminLocale = keyof typeof adminCopy;
export type AdminCopy = (typeof adminCopy)[AdminLocale];
